# @enabled on
# @id 2
# @storage_device custom-path
# @preserve_movies 0
# @lang en


width 1280
height 720
camera_name camera_2
auto_brightness off
framerate 30
target_dir /data/projects/animo-animo/animo-bee/runtime/camera_2
stream_localhost off
stream_port 9082
stream_maxrate 30
stream_quality 85
stream_motion off
stream_auth_method 0
text_left camera_2
text_right %Y-%m-%d\n%T
threshold 1500
noise_tune on
noise_level 32
minimum_motion_frames 20
picture_output off
movie_filename %Y-%m-%d/%H-%M-%S
movie_output on
movie_max_time 60
movie_codec mkv
movie_quality 45
on_event_start /opt/conda/lib/python3.13/site-packages/motioneye/scripts/relayevent.sh "./motioneye.conf" start %t
on_event_end /opt/conda/lib/python3.13/site-packages/motioneye/scripts/relayevent.sh "./motioneye.conf" stop %t
on_movie_end /opt/conda/lib/python3.13/site-packages/motioneye/scripts/relayevent.sh "./motioneye.conf" movie_end %t %f
on_picture_save /opt/conda/lib/python3.13/site-packages/motioneye/scripts/relayevent.sh "./motioneye.conf" picture_save %t %f
stream_authentication user:
video_device /dev/video1
