conf_path /data/projects/animo-animo/animo-bee/config/motioneye
run_path /data/projects/animo-animo/animo-bee/runtime/logs
log_path /data/projects/animo-animo/animo-bee/runtime/logs
media_path /data/projects/animo-animo/animo-bee/runtime
port 8765
